name: docker_commander
description: A Docker manager for local and remote host machines. Works with personalized containers and pre-configured popular containers, like PostgreSQL, Apache HTTPD and NGINX.
version: 2.1.8
homepage: https://github.com/gmpassos/docker_commander

environment:
  sdk: '>=3.6.0 <4.0.0'

executables:
  docker_commander_server:
  docker_commander_console:

dependencies:
  swiss_knife: ^3.3.5
  mercury_client: ^2.3.0
  logging: ^1.3.0
  collection: ^1.19.1
  apollovm: ^0.0.53
  version: ^3.0.2

dev_dependencies:
  lints: ^2.1.1
  test: ^1.29.0
  dependency_validator: ^3.2.3
  pubspec: ^2.3.0
  path: ^1.9.1

#dependency_overrides:
#  swiss_knife:
#    path: ../swiss_knife
#  mercury_client:
#    path: ../mercury_client
#  apollovm:
#    path: ../apollovm_dart
