name: docker_commander
description: A Docker manager for local and remote host machines. Works with personalized containers and pre-configured popular containers, like PostgreSQL, Apache HTTPD and NGINX.
version: 2.0.1
homepage: https://github.com/gmpassos/docker_commander

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  swiss_knife: ^3.0.6
  mercury_client: ^2.0.2
  logging: ^1.0.1
  collection: ^1.15.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  pubspec: ^2.0.1
  path: ^1.8.0

#dependency_overrides:
#  swiss_knife:
#    path: ../swiss_knife
#  mercury_client:
#    path: ../mercury_client

executables:
  docker_commander_server:
  docker_commander_console:


